using FluentAssertions;
using Moq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TrafficSimulation.Application.Vehicles;
using TrafficSimulation.Domain.Drivers;
using TrafficSimulation.Domain.Roads;
using TrafficSimulation.Domain.Vehicles;

namespace TrafficSimulation.Application.Test.Vehicles
{
    public class MoveVehicleCommandTest : RequestTestBase<MoveVehicleCommandHandler>
    {
        private readonly Mock<IVehicleService> mockVehicleService = new();

        public MoveVehicleCommandTest()
        {
            handler = new MoveVehicleCommandHandler(mockVehicleService.Object, mockLogger.Object);
        }

        [Theory]
        [MemberData(nameof(GenerateTraffic))]
        public async Task ShouldNavigateTraffic(TrafficExpectationModel model)
        {
            // Given
            mockVehicleService.Setup(x => x.GetNearby(It.IsAny<Vehicle>())).Returns(model.NearbyVehicles);

            // When
            var result = await handler.Handle(new MoveVehicleCommand
            {
                Road = model.Road,
                Vehicle = model.Vehicle
            }, CancellationToken.None);

            // Then
            result.Succeeded.Should().BeTrue();
            result.Response.Speed.Should().Be(model.ExpectedSpeed);
            result.Response.Position.LaneNumber.Should().Be(model.ExpectedLane);
            result.Response.Position.Front.Should().Be(model.ExpectedFront);
        }

        public static TheoryData<TrafficExpectationModel> GenerateTraffic =>
            new()
            {
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> (), Road = new Road { SpeedLimit = 55, Lanes = 1 }, ExpectedFront = 55, ExpectedLane = 0, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 35, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> (), Road = new Road { SpeedLimit = 55, Lanes = 1 }, ExpectedFront = 55, ExpectedLane = 0, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -115, Front = -100, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 1 }, ExpectedFront = 55, ExpectedLane = 0, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 0, Front = 15, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 55, ExpectedLane = 0, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 0, Front = 15, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -115, Front = -100, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 55, ExpectedLane = 1, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 1 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 55, ExpectedLane = 1, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 65, Driver = new Driver { DesiredSpeed = 65, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 985, Front = 1000, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 1 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 60, Front = 75, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 65, Driver = new Driver { DesiredSpeed = 65, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 985, Front = 1000, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 1 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 55, ExpectedLane = 1, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 55, ExpectedLane = 0, ExpectedSpeed = 55 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 35, Front = 50, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -5, Front = 10, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 65, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -45, Front = -30, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 65, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -115, Front = -100, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 0, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 35, Front = 50, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 1, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 1, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -5, Front = 10, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 1, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 1, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 65, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -45, Front = -30, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 1, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 1}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 1 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 65, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -115, Front = -100, LaneNumber = 0 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 45, ExpectedLane = 1, ExpectedSpeed = 45 },
                new() { Vehicle = new Vehicle { Id = Guid.NewGuid(), Speed = 55, Driver = new Driver{ DesiredSpeed = 55, FollowingInterval = 3 }, Position = new VehiclePosition { Back = -15, Front = 0, LaneNumber = 0}, VehicleType = VehicleTypes.Sedan }, NearbyVehicles = new List<Vehicle> { new Vehicle { Id = Guid.NewGuid(), Speed = 45, Driver = new Driver { DesiredSpeed = 45, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 85, Front = 100, LaneNumber = 0 } }, new Vehicle { Id = Guid.NewGuid(), Speed = 35, Driver = new Driver { DesiredSpeed = 35, FollowingInterval = 3 }, Position = new VehiclePosition { Back = 1185, Front = 1200, LaneNumber = 1 } } }, Road = new Road { SpeedLimit = 55, Lanes = 2 }, ExpectedFront = 55, ExpectedLane = 1, ExpectedSpeed = 55 },
            };
    }
}
